prebuildify --napi --target electron@11.3.0 --platform win32 --arch ia32
prebuildify --napi --target electron@11.3.0 --platform win32 --arch x64
prebuildify --napi --target electron@11.3.0 --platform win32 --arch arm64
prebuildify --napi --target electron@11.3.0 --platform darwin --arch x64
prebuildify --napi --target electron@11.3.0 --platform darwin --arch arm64
prebuildify --napi --target electron@11.3.0 --platform linux --arch ia32
prebuildify --napi --target electron@11.3.0 --platform linux --arch x64
prebuildify --napi --target electron@11.3.0 --platform linux --arch armhf
prebuildify --napi --target electron@11.3.0 --platform linux --arch arm64
